
name: create-configuration-csv
on:
  # This workflow runs when 'data/configuration.rda' is pushed or when triggered manually.
  push:
  #  paths:
  #    - 'data/configuration.rda'
  workflow_dispatch:

jobs:
  convert_data:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: install the here package
        run: install.packages(pkgs = c("here", "usethis"))
        shell: Rscript {0}

      - name: Run R script to load RDA
        run: Rscript data-raw/configuration.R

      - name: Run R script to convert RDA to CSV
        run: Rscript data-raw/create_configuration_csv.R

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: converted-csv
          path: data-raw/configuration.csv # Path to the generated CSV file
