
name: create-configuration-csv
on:
  # this workflow runs on pushing to main, pull requests to main, and manually.
  push:
    paths:
      - 'data/configuration.rda'

jobs:
  convert_data:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Run R script to convert RDA to CSV
        run: Rscript data-raw/create_configuration_csv.R

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: converted-csv
          path: data-raw/configuration.csv # Path to the generated CSV file
